preload = /home/cheetahportal/Pictures/NIER2_UPDATE.png
preload = /home/cheetahportal/Pictures/Nier1_with_full_black_border_UPDATE.png

wallpaper = DP-1,/home/cheetahportal/Pictures/NIER2_UPDATE.png
wallpaper = DP-2,/home/cheetahportal/Pictures/Nier1_with_full_black_border_UPDATE.png
